name: 🐛 Bug Report
description: Report a bug encountered while using Rancher Turtles
body:
  - type: textarea
    id: problem
    attributes:
      label: What steps did you take and what happened?
      placeholder: "A clear and concise description on how to REPRODUCE the bug."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce it?
    validations:
      required: false     

  - type: textarea
    id: rancherTurtles
    attributes:
      label: Rancher Turtles version
      placeholder: "The version of the Rancher Turtles used in the environment."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else you would like to add?
      placeholder: "Miscellaneous information that will assist in solving the issue."

  - type: textarea
    id: templateLabel
    attributes:
      label: Label(s) to be applied
      value: |
        /kind bug